spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: yukenz
    password: RbbQiXJmCcijnqOXc5Wtpz-FKaHSAMqW
    #    url: jdbc:mariadb://rpnis.railway.internal:3306/rpnis
    url: jdbc:mariadb://rpnisdb.railway.internal:3306/rpnis
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    springfox.documentation: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.jpa: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html