spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: awan
    url: jdbc:mariadb://localhost:3306/rpnis
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    springfox.documentation: DEBUG
    org.springframework.security: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html